Repository mykhaliuk/ghpr, pull requests merged in 2022-03, with the labels that each got.

#1 sort collabs
  dist/index.es.js
  dist/index.js
  package.json
  src/lib/createPR.ts
  src/lib/getCollabs.ts
Labels: bug, enhancement, automerge

#7 Fix: escape " in vars
  dist/index.es.js
  dist/index.js
  src/lib/PRBuilder.ts
  src/lib/api/client.ts
  src/lib/utils.ts
Labels: bug, automerge

#8 replace `replaceAll()` with `replace()`
  dist/index.es.js
  dist/index.js
  package.json
  src/lib/utils.ts
Labels: automerge

#10 Fix autcomplete limit
  dist/index.es.js
  dist/index.js
  package.json
  src/lib/PRBuilder.ts
Labels: automerge
